### ISSUE TITLE
У вас могут быть покупки по всем трём категориям

### ISSUE THREAD

**Issue by coursar** [Sergey2311/cashback#3]
https://github.com/Sergey2311/cashback/blob/151b194082f93ca7cb775ab5d1fd9b67152db49e/app.js#L3-L6

**Comment by Sergey2311** [comment]
Я не сделал третью категорию в коде, поскольку если не выпадают первые две, автоматически под условие попадает категория три. Фактически не было только названия. Следовал этой логике)

**Comment by coursar** [comment]
Ок, я совершил покупки по трём категориям:
1. По обычной - на 1 000 руб
2. По повышенной - на 10 000 руб
3. По специальной - на 100 000 руб

Кэшбек должен быть 3000 руб.

Как это укладывается в логику вашей программы?
